version: '3.8'

services:
  pdf-converter:
    build: .
    ports:
      - "${FLASK_PORT:-5000}:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FLASK_DEBUG=${FLASK_DEBUG:-false}
      - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
      - FLASK_PORT=${FLASK_PORT:-5000}
    env_file:
      - .env
    restart: unless-stopped
